host_domain: "test.jupyter.stfc.ac.uk"
ip_address: "130.246.213.116"
staging_cert: true

admin_names:
number_of_users:
username:

profiles:
  - profile1:
    display_name: "Default environment" 
    description: "This is a simple default environment"
    default: true
    image: jupyter/minimal-notebook 
    gpu_required: false
    commands:

iris_iam:
  required: false
  client_id:
  client_secret:
  admin_groups:
  allowed_groups:
