---
# Todo: Delete once Traefik is enabled on prod, or otherwise change the domain
# base_domain:
host_domain: "training.jupyter.stfc.ac.uk"
ip_address: "130.246.213.196"
longhorn_ip: "130.246.213.143"
staging_cert: false

use_traefik: false

profiles:
  - profile1:
    display_name: "Default environment"
    description: "This is a simple default environment"
    default: true
    # ram:
    image: jupyter/minimal-notebook
    node_groups: []
    gpu_required: false
    gpu_display_drivers: false
    # Please remove '-'s if no commands required
    commands:
      -
      -

# Uncomment to set users per gpu
# gpu_profiles:
#   - profile: users2
#     node_group: gpu
#   - profile: users3
#     node_group: gpu2

manila:
  required: false
  mount_path: "/home/jovyan/manila"
  share_name: new-cephfs-share-pvc

# One of ["shared_password", "iris_iam" or "keycloak"]:
# shared_password:
# Use the common authentication values below. All users share a password. All admins share another.

# keycloak:
# Use the common authentication values below, but deploy a Keycloak instance using additional settings below.
# Users/Admins are prompted to change their password ater first login

# iris_iam:
# Use the IRIS-IAM oauth service for authentication
authentication_method: "shared_password"

# These username/password options apply to shared_password and keycloak
common_authentication_values:
  # Passwords must be at least 32 characters for shared_password
  # For shared_password, these are permanent
  # For keycloak, these are temporary. Users/admins change them after first login
  admin_password:
  user_password:
  # This will be suffixed with "-1", "-2"...
  user_username_prefix:
  number_of_users:
  # These will be prefixed with "admin"
  admin_names:
    -
    -

keycloak:
  # Use traefik, or the loadbalancer IP's domain name
  domain: "keycloak.{{ base_domain }}"

  # Not used for Traefik
  loadBalancerIP:
  # A secret token for OIDC i.e. `openssl rand -hex 32`
  client_secret:
iris_iam:
  client_id:
  client_secret:
  admin_groups:
    -
    -
  allowed_groups:
    -
    -
