host_domain: "training.jupyter.stfc.ac.uk"
ip_address: "130.246.213.196"
longhorn_ip: "130.246.213.143"
staging_cert: false

admin_names:
  -
  -
number_of_users:
username:

profiles:
  - profile1:
    display_name: "Default environment" 
    description: "This is a simple default environment"
    default: true
    image: jupyter/minimal-notebook 
    gpu_required: false
    # Please remove '-'s if no commands required
    commands:
      -
      -

iris_iam:
  required: false
  client_id:
  client_secret:
  admin_groups:
    -
    -
  allowed_groups:
    -
    -
