- hosts: localhost
  tasks:

  - name: Set facts
    set_fact:
      kube_config: ~/.kube/cgtest.kubeconfig
      node_group: gpu2
      profile: users2

# check if config exists
  - name: Create GPU time share config map
    kubernetes.core.k8s:
      state: present
      kubeconfig: "{{ kube_config }}"
      definition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: ansible-test
          namespace: gpu-operator
        data:
            users2: |-
              version: v1
              sharing:
                timeSlicing:
                  resources:
                  - name: nvidia.com/gpu
                    replicas: 2
            users3: |-
              version: v1
              sharing:
                timeSlicing:
                  resources:
                  - name: nvidia.com/gpu
                    replicas: 3
            users4: |-
              version: v1
              sharing:
                timeSlicing:
                  resources:
                  - name: nvidia.com/gpu
                    replicas: 4


  # - name: Set default time slice configuration
  #   shell: 
  #     cmd: >
  #       kubectl patch clusterpolicies.nvidia.com/cluster-policy 
  #       -n gpu-operator 
  #       --type merge 
  #       -p '{"spec": {"devicePlugin": {"config": {"name": "time-slicing-config"}}}}' 
  #       --kubeconfig {{ kube_config }}

  - name: Patch config map
    kubernetes.core.k8s:
      api_version: nvidia.com/v1
      kind: ClusterPolicy
      name: cluster-policy
      kubeconfig: "{{ kube_config }}"
      namespace: gpu-operator
      merge_type:
        - merge
      definition:
        spec:
          devicePlugin:
            config:
              name: time-slicing-config

  # - name: Apply to GPU nodes
  #   shell: 
  #     cmd: >
  #       kubectl label nodes nvidia.com/device-plugin.config={{ profile }}
  #       -l capi.stackhpc.com/node-group={{ node_group }}
  #       --kubeconfig {{ kube_config }}
  #       --overwrite

  - name: Apply GPU label to nodes
    kubernetes.core.k8s:
      kubeconfig: "{{ kube_config }}"
      state: patched
      kind: Node
      name: nvidia.com/device-plugin.config={{ profile }}
      merge_type:
        - merge
      definition:
        metadata:
          labels:
            capi.stackhpc.com/node-group={{ node_group }}