---
- name: Template config file
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ jhub_config_file }}"
    mode: "0664"

- name: Install pre-set version of hub. This may take up to 25m to pull various images...
  kubernetes.core.helm:
    chart_ref: "{{ jhub_chart_ref }}"
    chart_repo_url: "{{ jhub_repo_url }}"
    release_name: "{{ jhub_deployed_name }}"
    chart_version: "{{ jhub_version }}"
    release_namespace: "{{ jhub_namespace }}"
    create_namespace: true
    kubeconfig: "{{ kubeconfig_path }}"
    wait: true
    values_files:
      - "{{ jhub_config_file }}"
    timeout: "25m"
