---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # "unsafe" is required if we add ansible-vault in future
      # but it will also disable duplicate-key checks
      # ansible-lint --fix also yaml lints, but set that to pre-push only
      - id: check-yaml
      # args: ["--unsafe"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/ansible/ansible-lint
    rev: v25.9.2
    hooks:
      - id: ansible-lint
        args: ["--fix"]
        language_version: python3.11
        additional_dependencies:
          - ansible==9.4.0
          - ansible-core==2.16.14
          - ansible-compat==25.8.2
        exclude: ^\.ansible/
