apiVersion: v1
kind: ConfigMap
metadata: 
  name: time-slicing-config-fine
data:
  NVIDIA-RTX-A4000: |-
    version: v1
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 2
  users3: |-
    version: v1
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 3
