---
- name: Get pods
  kubernetes.core.k8s_info:
    kind: pod
    namespace: jupyterhub
    field_selectors:
      - spec.serviceAccountName=autohttps
    kubeconfig: "{{ kubeconfig_path }}"
  register: pods

- name: Get pod name
  ansible.builtin.set_fact:
    pod_name: "{{ pods.resources | map(attribute='metadata.name') | list | first }}"

- name: Delete/restart autohttps pod
  kubernetes.core.k8s:
    api_version: v1
    kind: pod
    namespace: jupyterhub
    name: "{{ pod_name }}"
    state: absent
    wait: true
    kubeconfig: "{{ kubeconfig_path }}"
