- name: Create jupyterhub namespace
  kubernetes.core.k8s:
    name: jupyterhub
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ kube_config }}"

- name: Check if admin password exists
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: adminpassword
    namespace: jupyterhub
    kubeconfig: "{{ kube_config }}"
  register: admin_exists

- name: Check if user password exists
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: userpassword
    namespace: jupyterhub
    kubeconfig: "{{ kube_config }}"
  register: user_exists

- name: Generate admin password
  when: admin_exists.resources | length == 0
  block:
  
    - name: Generate admin password
      ansible.builtin.set_fact: 
        adminpassword: "{{ lookup('community.general.random_string', length=32, base64=True) }}"

    - name: Store admin password in kubernetes
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: adminpassword
            namespace: jupyterhub
          type: Opaque
          stringData:
            password: "{{ adminpassword }}"
        kubeconfig: "{{ kube_config }}"

- name: Generate user password
  when: user_exists.resources | length == 0
  block:
  
    - name: Generate user password
      ansible.builtin.set_fact:
        userpassword: "{{ lookup('community.general.random_string', length=32, base64=True) }}"

    - name: Store user password in kubernetes
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: userpassword
            namespace: jupyterhub
          type: Opaque
          stringData:
            password: "{{ userpassword }}"
        kubeconfig: "{{ kube_config }}"

- name: Get admin password from kubernetes
  when: admin_exists.resources | length > 0
  block:
    - name: Read admin password from kubernetes
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: adminpassword
        namespace: jupyterhub
        kubeconfig: "{{ kube_config }}"
      register: admin_secret

    - name: Store admin password as ansible variable
      ansible.builtin.set_fact:
        adminpassword: "{{ admin_secret.resources[0].data.password | b64decode }}"

- name: Get user password from kubernetes
  when: user_exists.resources | length > 0
  block:
    - name: Read user password from kubernetes
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: userpassword
        namespace: jupyterhub
        kubeconfig: "{{ kube_config }}"
      register: user_secret

    - name: Store user password as ansible variable
      ansible.builtin.set_fact:
        userpassword: "{{ user_secret.resources[0].data.password | b64decode }}"
